# 7-Numpy_Pandas


In [ ]:
# Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# Exercise 2: Extract elements between 5th and 15th index

In [5]:
arr2 = np.arange(1, 21)
extracted = arr2[5:16]
print(extracted)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [6]:
# Exercise 3: Create and modify a Pandas Series

In [7]:
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series['pears'] = 4
print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [8]:
# Exercise 4: Create a DataFrame

In [9]:
people = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 27, 32, 45, 50, 29],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}
df = pd.DataFrame(people)
print(df)


      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eve   22      F
5    Frank   27      M
6    Grace   32      F
7    Helen   45      F
8      Ivy   50      F
9     Jack   29      M


In [10]:
# Exercise 5: Add occupation column

In [11]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5    Frank   27      M     Analyst
6    Grace   32      F  Programmer
7    Helen   45      F     Manager
8      Ivy   50      F     Analyst
9     Jack   29      M  Programmer


In [12]:
# Exercise 6: Select rows where age >= 30

In [13]:
filtered_df = df[df['age'] >= 30]
print(filtered_df)

      name  age gender  occupation
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
6    Grace   32      F  Programmer
7    Helen   45      F     Manager
8      Ivy   50      F     Analyst


In [14]:
# Exercise 7: Convert DataFrame to CSV and read it back

In [15]:
df.to_csv('people.csv', index=False)
df_read = pd.read_csv('people.csv')
print(df_read)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5    Frank   27      M     Analyst
6    Grace   32      F  Programmer
7    Helen   45      F     Manager
8      Ivy   50      F     Analyst
9     Jack   29      M  Programmer
